### ISSUE TITLE
Overlapping/sub-basins

### ISSUE THREAD

**Issue by Daafip** [eWaterCycle/caravan-map#1]
@BSchilperoort tried the Czech map, but it seems like I'm not able to select any of the sub-basins, as the polygons overlap

https://www.ewatercycle.org/caravan-map/caravan_catchments_map_Czech_Republic.html

(Copied from https://github.com/Daafip/caravan-map/issues/1)

**Comment by Daafip** [comment]
Seems to be an issue in more places, Ill look into it. 
Quickest fix is to add the popup only at the centroid. 
Since the overlap in basins is almost never with the same centre this will fix it.

Nice is to do a geometric operation which ensures this isn't the case

**Comment by BSchilperoort** [comment]
> Nice is to do a geometric operation which ensures this isn't the case

You would probably want to draw the smallest basins last. So if you sort all polygons by their area, and draw the largest ones first and smallest ones last this issue can be avoided.

**Comment by Daafip** [comment]
Smart! that fixes it
